# Generated by Django 2.0.3 on 2020-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
