# Generated by Django 2.1.5 on 2020-05-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pizza_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='count',
            new_name='price',
        ),
        migrations.AddField(
            model_name='pizza',
            name='kind',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
