# Generated by Django 2.1.5 on 2020-05-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_subs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subs',
            new_name='Subs_small',
        ),
    ]
