# Generated by Django 2.1.5 on 2020-05-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_dinner_pasta_salads_subs_large'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner',
            old_name='prize',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='prize',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='salads',
            old_name='prize',
            new_name='price',
        ),
    ]
