# Generated by Django 2.1.5 on 2020-05-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200504_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='small',
            name='id',
        ),
        migrations.AddField(
            model_name='small',
            name='small_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
