# Generated by Django 2.1.5 on 2020-05-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200505_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='id',
        ),
        migrations.AddField(
            model_name='topping',
            name='topping_id',
            field=models.IntegerField(default=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
