# Generated by Django 2.1.5 on 2020-05-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200505_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs_small',
            name='id',
        ),
        migrations.AddField(
            model_name='subs_small',
            name='subs_s_id',
            field=models.IntegerField(default=300, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
