# Generated by Django 2.1.5 on 2020-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200505_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs_large',
            name='id',
        ),
        migrations.AddField(
            model_name='subs_large',
            name='subs_l_id',
            field=models.IntegerField(default=400, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
