# Generated by Django 2.1.5 on 2020-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200505_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='id',
        ),
        migrations.AddField(
            model_name='pasta',
            name='pasta_id',
            field=models.IntegerField(default=500, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
