# Generated by Django 2.1.5 on 2020-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200505_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='id',
        ),
        migrations.AddField(
            model_name='dinner',
            name='dinner_id',
            field=models.IntegerField(default=700, primary_key=700, serialize=False),
            preserve_default=False,
        ),
    ]
