# Generated by Django 2.1.5 on 2020-05-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200505_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner',
            old_name='dinner_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='large',
            old_name='large_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='pasta_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='salads',
            old_name='salad_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='small',
            old_name='small_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subs_large',
            old_name='subs_l_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subs_small',
            old_name='subs_s_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='topping_id',
            new_name='id',
        ),
    ]
