# Generated by Django 2.1.5 on 2020-05-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200506_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='large',
            old_name='kind',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='small',
            old_name='kind',
            new_name='name',
        ),
    ]
